# Generated by Django 2.2.6 on 2019-11-19 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_model', models.CharField(help_text='Ingrese el modelo del auto', max_length=50)),
                ('car_plate', models.CharField(default='abcd21', max_length=6, primary_key=True, serialize=False)),
                ('car_price', models.IntegerField(help_text='Ingrese precio estimado de venta')),
                ('car_category', models.CharField(default='---', help_text='Ingrese la categoria/disciplina del vehiculo', max_length=30)),
                ('car_year', models.IntegerField(help_text='Ingrese el año del auto')),
                ('car_engine', models.CharField(default='---', help_text='Ingrese el tipo de motor del vehiculo', max_length=30)),
                ('car_cilindrada', models.FloatField(help_text='Ingrese la cilindrada del motor')),
                ('car_drivetrain', models.CharField(choices=[('4WD', '/Four Wheel Drive / Traccion Integral'), ('AWD', 'All Wheel Drive / Traccion Total'), ('FWD', 'Front Wheel Drive / Traccion Delantera'), ('RWD', 'Rear Whell Drive / Traccion Trasera')], default='---3', help_text='Ingrese la opcion de traccion que posea el vehiculo', max_length=3)),
                ('car_brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Brand')),
            ],
        ),
    ]
