# Generated by Django 2.2.6 on 2019-11-20 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['brand_name']},
        ),
    ]
