# Generated by Django 2.2.6 on 2019-11-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20191120_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_plate',
            field=models.IntegerField(default='111111', primary_key=True, serialize=False),
        ),
    ]
